### PR TITLE
Redoing everything

### PR DESCRIPTION
**Pull request by 808dkaneohe**

### CODE REVIEW

**Comment by 808dkaneohe** [comment]
This is probably going to fuck something over but who cares

**Comment by LionWaffles** [comment]
you broke everything... lol.

**Comment by SirFrancisBillard** [comment]
"probably going to fuck something over"

nice one

**Comment by 808dkaneohe** [comment]
it's bc I have to redo all the css xd

**Comment by LionWaffles** [comment]
No shit, the website looks janky af.

**Pull request merged**
